### ISSUE TITLE
Index on bulkInsert

### ISSUE THREAD

**Issue by marcoancona** [doriandrn/rxdb-search#1]
Hi! Nice work here, I was looking for a way to add full-text search on rxdb and I found this very recent project. Let me know if you need help, I would be happy to contribute.

In the meanwhile, I am facing a problem with rxdb `bulkInsert` method: this does not seem to trigger any of the hooks and therefore the indices are not created. As a workaround (and nice-to-have feature), what about exposing a method to create an index for some given new documents. Could also recycle the existing `index()`:

- `collection.index()` --> runs full index creation
- `collection.index(docs)` --> index all documents in docs

**Comment by doriandrn** [comment]
Hey Marco,

Thank you! Being a really small project right now, everything seems under control so far, hehe, but please feel free to contribute at anytime if it's beneficial! I'm able to help/assist too.

Ugh.., wished RxDB triggered the `.postInsert` hook on `.bulkInsert` too but it seems it's not the case right now, maybe we should open an issue for this; But thanks for suggesting this, your point totally makes sense and as I'm also using .bulkInsert, I've went ahead and implemented this. v1.0.10 is on it's way!
